{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TemplateHaskellQuotes #-}

module Database.Kosem.PostgreSQL.Internal.PgBuiltin where

import Data.Text (Text)
import Database.Kosem.PostgreSQL.Internal.PgType qualified as PgType
import Database.Kosem.PostgreSQL.Internal.TypCategory qualified as TypCategory
import Database.Kosem.PostgreSQL.Internal.Types
import Language.Haskell.TH (Name)

data DatabaseConfig = DatabaseConfig
    { types :: [(Identifier, PgType)]
    , typesToHs :: [(PgType, Name)]
    , binaryOperators :: [(Operator, PgType, PgType, PgType)]
    , confFunctions :: [(Identifier, [PgType], PgType)]
    }

defaultDatabaseConfig :: DatabaseConfig
defaultDatabaseConfig =
    DatabaseConfig
        { types =
            [ ("text", PgType.Text)
            , ("integer", PgType.Integer)
            , ("bigint", PgType.Bigint)
            , ("boolean", PgType.Boolean)
            ]
        , typesToHs =
            [ (PgType.Text, ''Text)
            , (PgType.Integer, ''Int)
            , (PgType.Bigint, ''Int)
            , (PgType.Boolean, ''Bool)
            ]
        , binaryOperators = pgbinaryOperators
        , confFunctions = pgFunctions
        }

-- * Operators

pgbinaryOperators :: [(Operator, PgType, PgType, PgType)]
pgbinaryOperators =
    {- Generated by this query:
         ```sql
         with kosem_types as (
             select *
               from (values
               ('integer'), ('bigint'), ('text'),
             (  'boolean'), ('numeric'), ('unkwnown')) as ty
         ), gpt_rank (gpt_rank, op) as (
         -- We order operators by their usage ranking, courtesy of ChatGPT.
             select row_number() over (), *
               from (values
             ('='), ('<>'), ('<'), ('<='), ('>'), ('>='),
             ('+'), ('-'), ('*'), ('/'), ('%'), ('&'),
             ('|'), ('#'), ('||'), ('->'), ('->>'), ('#>'),
             ('#>>'), ('@>'), ('<@')) as op
         ), bin_operators as (
             select * from (
                 select
                     o.oprname AS operator_name,
                     pg_catalog.format_type(o.oprleft, NULL) AS left_type,
                     pg_catalog.format_type(o.oprright, NULL) AS right_type,
                     pg_catalog.format_type(o.oprresult, NULL) AS result_type
                   from pg_catalog.pg_operator o
                   left join pg_catalog.pg_type t ON o.oprresult = t.oid
             ) _
               left join gpt_rank on op = operator_name
              where left_type in (select * from kosem_types)
                and right_type in (select * from kosem_types)
                and result_type in (select * from kosem_types)
              order by
              coalesce(gpt_rank, 99), result_type, operator_name, left_type, right_type
         )
         select '    ' || ', ("' || operator_name || '", '
             || 'Pg' || initcap(left_type) || ', '
             || 'Pg' || initcap(right_type) || ', '
             || 'Pg' || initcap(result_type) || ')'
           from bin_operators;
         ```
    -}
    [ ("=", PgType.Bigint, PgType.Bigint, PgType.Boolean)
    , ("=", PgType.Bigint, PgType.Integer, PgType.Boolean)
    , ("=", PgType.Bigint, PgType.Smallint, PgType.Boolean)
    , ("=", PgType.Boolean, PgType.Boolean, PgType.Boolean)
    , ("=", PgType.Character, PgType.Character, PgType.Boolean)
    , ("=", PgType.DoublePrecision, PgType.DoublePrecision, PgType.Boolean)
    , ("=", PgType.DoublePrecision, PgType.Real, PgType.Boolean)
    , ("=", PgType.Integer, PgType.Bigint, PgType.Boolean)
    , ("=", PgType.Integer, PgType.Integer, PgType.Boolean)
    , ("=", PgType.Integer, PgType.Smallint, PgType.Boolean)
    , ("=", PgType.Numeric, PgType.Numeric, PgType.Boolean)
    , ("=", PgType.Real, PgType.DoublePrecision, PgType.Boolean)
    , ("=", PgType.Real, PgType.Real, PgType.Boolean)
    , ("=", PgType.Smallint, PgType.Bigint, PgType.Boolean)
    , ("=", PgType.Smallint, PgType.Integer, PgType.Boolean)
    , ("=", PgType.Smallint, PgType.Smallint, PgType.Boolean)
    , ("=", PgType.Text, PgType.Text, PgType.Boolean)
    , ("<>", PgType.Bigint, PgType.Bigint, PgType.Boolean)
    , ("<>", PgType.Bigint, PgType.Integer, PgType.Boolean)
    , ("<>", PgType.Bigint, PgType.Smallint, PgType.Boolean)
    , ("<>", PgType.Boolean, PgType.Boolean, PgType.Boolean)
    , ("<>", PgType.Character, PgType.Character, PgType.Boolean)
    , ("<>", PgType.DoublePrecision, PgType.DoublePrecision, PgType.Boolean)
    , ("<>", PgType.DoublePrecision, PgType.Real, PgType.Boolean)
    , ("<>", PgType.Integer, PgType.Bigint, PgType.Boolean)
    , ("<>", PgType.Integer, PgType.Integer, PgType.Boolean)
    , ("<>", PgType.Integer, PgType.Smallint, PgType.Boolean)
    , ("<>", PgType.Numeric, PgType.Numeric, PgType.Boolean)
    , ("<>", PgType.Real, PgType.DoublePrecision, PgType.Boolean)
    , ("<>", PgType.Real, PgType.Real, PgType.Boolean)
    , ("<>", PgType.Smallint, PgType.Bigint, PgType.Boolean)
    , ("<>", PgType.Smallint, PgType.Integer, PgType.Boolean)
    , ("<>", PgType.Smallint, PgType.Smallint, PgType.Boolean)
    , ("<>", PgType.Text, PgType.Text, PgType.Boolean)
    , ("<", PgType.Bigint, PgType.Bigint, PgType.Boolean)
    , ("<", PgType.Bigint, PgType.Integer, PgType.Boolean)
    , ("<", PgType.Bigint, PgType.Smallint, PgType.Boolean)
    , ("<", PgType.Boolean, PgType.Boolean, PgType.Boolean)
    , ("<", PgType.Character, PgType.Character, PgType.Boolean)
    , ("<", PgType.DoublePrecision, PgType.DoublePrecision, PgType.Boolean)
    , ("<", PgType.DoublePrecision, PgType.Real, PgType.Boolean)
    , ("<", PgType.Integer, PgType.Bigint, PgType.Boolean)
    , ("<", PgType.Integer, PgType.Integer, PgType.Boolean)
    , ("<", PgType.Integer, PgType.Smallint, PgType.Boolean)
    , ("<", PgType.Numeric, PgType.Numeric, PgType.Boolean)
    , ("<", PgType.Real, PgType.DoublePrecision, PgType.Boolean)
    , ("<", PgType.Real, PgType.Real, PgType.Boolean)
    , ("<", PgType.Smallint, PgType.Bigint, PgType.Boolean)
    , ("<", PgType.Smallint, PgType.Integer, PgType.Boolean)
    , ("<", PgType.Smallint, PgType.Smallint, PgType.Boolean)
    , ("<", PgType.Text, PgType.Text, PgType.Boolean)
    , ("<=", PgType.Bigint, PgType.Bigint, PgType.Boolean)
    , ("<=", PgType.Bigint, PgType.Integer, PgType.Boolean)
    , ("<=", PgType.Bigint, PgType.Smallint, PgType.Boolean)
    , ("<=", PgType.Boolean, PgType.Boolean, PgType.Boolean)
    , ("<=", PgType.Character, PgType.Character, PgType.Boolean)
    , ("<=", PgType.DoublePrecision, PgType.DoublePrecision, PgType.Boolean)
    , ("<=", PgType.DoublePrecision, PgType.Real, PgType.Boolean)
    , ("<=", PgType.Integer, PgType.Bigint, PgType.Boolean)
    , ("<=", PgType.Integer, PgType.Integer, PgType.Boolean)
    , ("<=", PgType.Integer, PgType.Smallint, PgType.Boolean)
    , ("<=", PgType.Numeric, PgType.Numeric, PgType.Boolean)
    , ("<=", PgType.Real, PgType.DoublePrecision, PgType.Boolean)
    , ("<=", PgType.Real, PgType.Real, PgType.Boolean)
    , ("<=", PgType.Smallint, PgType.Bigint, PgType.Boolean)
    , ("<=", PgType.Smallint, PgType.Integer, PgType.Boolean)
    , ("<=", PgType.Smallint, PgType.Smallint, PgType.Boolean)
    , ("<=", PgType.Text, PgType.Text, PgType.Boolean)
    , (">", PgType.Bigint, PgType.Bigint, PgType.Boolean)
    , (">", PgType.Bigint, PgType.Integer, PgType.Boolean)
    , (">", PgType.Bigint, PgType.Smallint, PgType.Boolean)
    , (">", PgType.Boolean, PgType.Boolean, PgType.Boolean)
    , (">", PgType.Character, PgType.Character, PgType.Boolean)
    , (">", PgType.DoublePrecision, PgType.DoublePrecision, PgType.Boolean)
    , (">", PgType.DoublePrecision, PgType.Real, PgType.Boolean)
    , (">", PgType.Integer, PgType.Bigint, PgType.Boolean)
    , (">", PgType.Integer, PgType.Integer, PgType.Boolean)
    , (">", PgType.Integer, PgType.Smallint, PgType.Boolean)
    , (">", PgType.Numeric, PgType.Numeric, PgType.Boolean)
    , (">", PgType.Real, PgType.DoublePrecision, PgType.Boolean)
    , (">", PgType.Real, PgType.Real, PgType.Boolean)
    , (">", PgType.Smallint, PgType.Bigint, PgType.Boolean)
    , (">", PgType.Smallint, PgType.Integer, PgType.Boolean)
    , (">", PgType.Smallint, PgType.Smallint, PgType.Boolean)
    , (">", PgType.Text, PgType.Text, PgType.Boolean)
    , (">=", PgType.Bigint, PgType.Bigint, PgType.Boolean)
    , (">=", PgType.Bigint, PgType.Integer, PgType.Boolean)
    , (">=", PgType.Bigint, PgType.Smallint, PgType.Boolean)
    , (">=", PgType.Boolean, PgType.Boolean, PgType.Boolean)
    , (">=", PgType.Character, PgType.Character, PgType.Boolean)
    , (">=", PgType.DoublePrecision, PgType.DoublePrecision, PgType.Boolean)
    , (">=", PgType.DoublePrecision, PgType.Real, PgType.Boolean)
    , (">=", PgType.Integer, PgType.Bigint, PgType.Boolean)
    , (">=", PgType.Integer, PgType.Integer, PgType.Boolean)
    , (">=", PgType.Integer, PgType.Smallint, PgType.Boolean)
    , (">=", PgType.Numeric, PgType.Numeric, PgType.Boolean)
    , (">=", PgType.Real, PgType.DoublePrecision, PgType.Boolean)
    , (">=", PgType.Real, PgType.Real, PgType.Boolean)
    , (">=", PgType.Smallint, PgType.Bigint, PgType.Boolean)
    , (">=", PgType.Smallint, PgType.Integer, PgType.Boolean)
    , (">=", PgType.Smallint, PgType.Smallint, PgType.Boolean)
    , (">=", PgType.Text, PgType.Text, PgType.Boolean)
    , ("+", PgType.Bigint, PgType.Bigint, PgType.Bigint)
    , ("+", PgType.Bigint, PgType.Integer, PgType.Bigint)
    , ("+", PgType.Bigint, PgType.Smallint, PgType.Bigint)
    , ("+", PgType.Integer, PgType.Bigint, PgType.Bigint)
    , ("+", PgType.Smallint, PgType.Bigint, PgType.Bigint)
    , ("+", PgType.DoublePrecision, PgType.DoublePrecision, PgType.DoublePrecision)
    , ("+", PgType.DoublePrecision, PgType.Real, PgType.DoublePrecision)
    , ("+", PgType.Real, PgType.DoublePrecision, PgType.DoublePrecision)
    , ("+", PgType.Integer, PgType.Integer, PgType.Integer)
    , ("+", PgType.Integer, PgType.Smallint, PgType.Integer)
    , ("+", PgType.Smallint, PgType.Integer, PgType.Integer)
    , ("+", PgType.Numeric, PgType.Numeric, PgType.Numeric)
    , ("+", PgType.Real, PgType.Real, PgType.Real)
    , ("+", PgType.Smallint, PgType.Smallint, PgType.Smallint)
    , ("-", PgType.Bigint, PgType.Bigint, PgType.Bigint)
    , ("-", PgType.Bigint, PgType.Integer, PgType.Bigint)
    , ("-", PgType.Bigint, PgType.Smallint, PgType.Bigint)
    , ("-", PgType.Integer, PgType.Bigint, PgType.Bigint)
    , ("-", PgType.Smallint, PgType.Bigint, PgType.Bigint)
    , ("-", PgType.DoublePrecision, PgType.DoublePrecision, PgType.DoublePrecision)
    , ("-", PgType.DoublePrecision, PgType.Real, PgType.DoublePrecision)
    , ("-", PgType.Real, PgType.DoublePrecision, PgType.DoublePrecision)
    , ("-", PgType.Integer, PgType.Integer, PgType.Integer)
    , ("-", PgType.Integer, PgType.Smallint, PgType.Integer)
    , ("-", PgType.Smallint, PgType.Integer, PgType.Integer)
    , ("-", PgType.Numeric, PgType.Numeric, PgType.Numeric)
    , ("-", PgType.Real, PgType.Real, PgType.Real)
    , ("-", PgType.Smallint, PgType.Smallint, PgType.Smallint)
    , ("*", PgType.Bigint, PgType.Bigint, PgType.Bigint)
    , ("*", PgType.Bigint, PgType.Integer, PgType.Bigint)
    , ("*", PgType.Bigint, PgType.Smallint, PgType.Bigint)
    , ("*", PgType.Integer, PgType.Bigint, PgType.Bigint)
    , ("*", PgType.Smallint, PgType.Bigint, PgType.Bigint)
    , ("*", PgType.DoublePrecision, PgType.DoublePrecision, PgType.DoublePrecision)
    , ("*", PgType.DoublePrecision, PgType.Real, PgType.DoublePrecision)
    , ("*", PgType.Real, PgType.DoublePrecision, PgType.DoublePrecision)
    , ("*", PgType.Integer, PgType.Integer, PgType.Integer)
    , ("*", PgType.Integer, PgType.Smallint, PgType.Integer)
    , ("*", PgType.Smallint, PgType.Integer, PgType.Integer)
    , ("*", PgType.Numeric, PgType.Numeric, PgType.Numeric)
    , ("*", PgType.Real, PgType.Real, PgType.Real)
    , ("*", PgType.Smallint, PgType.Smallint, PgType.Smallint)
    , ("/", PgType.Bigint, PgType.Bigint, PgType.Bigint)
    , ("/", PgType.Bigint, PgType.Integer, PgType.Bigint)
    , ("/", PgType.Bigint, PgType.Smallint, PgType.Bigint)
    , ("/", PgType.Integer, PgType.Bigint, PgType.Bigint)
    , ("/", PgType.Smallint, PgType.Bigint, PgType.Bigint)
    , ("/", PgType.DoublePrecision, PgType.DoublePrecision, PgType.DoublePrecision)
    , ("/", PgType.DoublePrecision, PgType.Real, PgType.DoublePrecision)
    , ("/", PgType.Real, PgType.DoublePrecision, PgType.DoublePrecision)
    , ("/", PgType.Integer, PgType.Integer, PgType.Integer)
    , ("/", PgType.Integer, PgType.Smallint, PgType.Integer)
    , ("/", PgType.Smallint, PgType.Integer, PgType.Integer)
    , ("/", PgType.Numeric, PgType.Numeric, PgType.Numeric)
    , ("/", PgType.Real, PgType.Real, PgType.Real)
    , ("/", PgType.Smallint, PgType.Smallint, PgType.Smallint)
    , ("%", PgType.Bigint, PgType.Bigint, PgType.Bigint)
    , ("%", PgType.Integer, PgType.Integer, PgType.Integer)
    , ("%", PgType.Numeric, PgType.Numeric, PgType.Numeric)
    , ("%", PgType.Smallint, PgType.Smallint, PgType.Smallint)
    , ("&", PgType.Bigint, PgType.Bigint, PgType.Bigint)
    , ("&", PgType.Integer, PgType.Integer, PgType.Integer)
    , ("&", PgType.Smallint, PgType.Smallint, PgType.Smallint)
    , ("|", PgType.Bigint, PgType.Bigint, PgType.Bigint)
    , ("|", PgType.Integer, PgType.Integer, PgType.Integer)
    , ("|", PgType.Smallint, PgType.Smallint, PgType.Smallint)
    , ("#", PgType.Bigint, PgType.Bigint, PgType.Bigint)
    , ("#", PgType.Integer, PgType.Integer, PgType.Integer)
    , ("#", PgType.Smallint, PgType.Smallint, PgType.Smallint)
    , ("||", PgType.Text, PgType.Text, PgType.Text)
    , ("<<", PgType.Bigint, PgType.Integer, PgType.Bigint)
    , (">>", PgType.Bigint, PgType.Integer, PgType.Bigint)
    , ("!~", PgType.Character, PgType.Text, PgType.Boolean)
    , ("!~", PgType.Text, PgType.Text, PgType.Boolean)
    , ("!~*", PgType.Character, PgType.Text, PgType.Boolean)
    , ("!~*", PgType.Text, PgType.Text, PgType.Boolean)
    , ("!~~", PgType.Character, PgType.Text, PgType.Boolean)
    , ("!~~", PgType.Text, PgType.Text, PgType.Boolean)
    , ("!~~*", PgType.Character, PgType.Text, PgType.Boolean)
    , ("!~~*", PgType.Text, PgType.Text, PgType.Boolean)
    , ("@@", PgType.Text, PgType.Text, PgType.Boolean)
    , ("^@", PgType.Text, PgType.Text, PgType.Boolean)
    , ("~", PgType.Character, PgType.Text, PgType.Boolean)
    , ("~", PgType.Text, PgType.Text, PgType.Boolean)
    , ("~*", PgType.Character, PgType.Text, PgType.Boolean)
    , ("~*", PgType.Text, PgType.Text, PgType.Boolean)
    , ("~<=~", PgType.Character, PgType.Character, PgType.Boolean)
    , ("~<=~", PgType.Text, PgType.Text, PgType.Boolean)
    , ("~<~", PgType.Character, PgType.Character, PgType.Boolean)
    , ("~<~", PgType.Text, PgType.Text, PgType.Boolean)
    , ("~>=~", PgType.Character, PgType.Character, PgType.Boolean)
    , ("~>=~", PgType.Text, PgType.Text, PgType.Boolean)
    , ("~>~", PgType.Character, PgType.Character, PgType.Boolean)
    , ("~>~", PgType.Text, PgType.Text, PgType.Boolean)
    , ("~~", PgType.Character, PgType.Text, PgType.Boolean)
    , ("~~", PgType.Text, PgType.Text, PgType.Boolean)
    , ("~~*", PgType.Character, PgType.Text, PgType.Boolean)
    , ("~~*", PgType.Text, PgType.Text, PgType.Boolean)
    , ("^", PgType.DoublePrecision, PgType.DoublePrecision, PgType.DoublePrecision)
    , ("<<", PgType.Integer, PgType.Integer, PgType.Integer)
    , (">>", PgType.Integer, PgType.Integer, PgType.Integer)
    , ("^", PgType.Numeric, PgType.Numeric, PgType.Numeric)
    , ("<<", PgType.Smallint, PgType.Integer, PgType.Smallint)
    , (">>", PgType.Smallint, PgType.Integer, PgType.Smallint)
    ]

pgFunctions :: [(Identifier, [PgType], PgType)]
pgFunctions =
    [ ("length", [PgType.Text], PgType.Integer)
    , ("replace", [PgType.Text, PgType.Text, PgType.Text], PgType.Text)
    ]
